[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "win-64", "osx-arm64"]
preview = ["pixi-build"]



[package]
authors = ["Davide Gorbani <davide.gorbani@iit.it>"]
name = "ironcub-models"
version = "0.0.2"

[tasks]

[dependencies]
ironcub-models = { path = "." }

[package.build.backend]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
name = "pixi-build-cmake"
version = "*"

[package.run-dependencies]
# This is just a workaround: we should add the conda prefix to ROS_PACKAGE_PATH and AMENT_PREFIX_PATH, 
# but this is not supported at the moment by pixi build, so we just add a dependency on a package
# that set those variables
ergocub-models = "*"
